Add SHA1 suffix to intermediaries
FabricMC/fabric-loom pull request #1141
Opened 2024-07-06 11:57 UTC by Wyvest

Having two or more different intermediaries for one version breaks. Although this isn't possible in vanilla Loom, one example would be loading Legacy Forge 1.8.9 and Legacy Fabric 1.8.9 in one project.
Attaching a differentiating name to each intermediary we download, we use this to differentiate between intermediaries.

To be honest I made this around a year ago and never PRed it here so this might be a really terrible approach. Please feel free to give feedback.

2024-07-14 16:16 UTC, modmuss50 reviewed
I dont think we need this for official intermediary names.

2024-07-14 16:38 UTC, SpaceWalkerRS commented
Isnt this what the different intermediary providers are for? You can create a new provider and change the name and it'll end up in a different cache file.

2024-07-15 10:19 UTC, modmuss50 requested changes

2024-07-15 10:19 UTC, modmuss50 commented on src/main/java/net/fabricmc/loom/configuration/providers/mappings/IntermediaryMappingsProvider.java
> +	private String getSha1(String value) {
Loom already has a helper for this, see Checksum.sha1Hex

2024-07-15 10:19 UTC, modmuss50 commented on src/main/java/net/fabricmc/loom/configuration/providers/mappings/IntermediaryMappingsProvider.java
> +		if (!LoomGradleExtensionApiImpl.DEFAULT_INTERMEDIARY_URL.equals(urlRaw)) {
This wont build due to checkstyle, please make sure it builds and actually works by testing it.

I dont see an automated test for this (likely becuase its quite hard to test), so it definitely should be manually tested.

2024-07-16 12:09 UTC, modmuss50 approved these changes

2024-07-16 12:57 UTC, Wyvest commented
> Isnt this what the different intermediary providers are for? You can create a new provider and change the name and it'll end up in a different cache file.

Using the loom extension in your buildscript you can only set the intermediary URL. Besides, it isn't specified that you have to change the name and URL for it to work.

2024-07-16 12:59 UTC, Octol1ttle commented on src/main/java/net/fabricmc/loom/configuration/providers/mappings/IntermediaryMappingsProvider.java
> +		final String encodedMcVersion = UrlEscapers.urlFragmentEscaper().escape(getMinecraftVersion().get());
Wouldn't it be better to have this inside the `if` block (since that is the only place where it is used)?

2024-09-03 17:11 UTC, merged