Add descriptions to all the tasks
FabricMC/fabric-loom pull request #214
Opened 2020-05-29 14:33 UTC by RDIL

Adds descriptions so people who execute `gradle tasks` will get descriptions of what all Loom's tasks will do.

2020-05-29 14:50 UTC, natanfudge approved these changes
Sure

2020-05-29 14:55 UTC, Juuxel requested changes
Fixed some inconsistency with verbs (`generate` vs `generates` etc.) and some mistakes in the descriptions themselves.

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +		tasks.register("cleanLoomMappings", CleanLoomMappings.class, t -> t.setDescription("Remove mappings downloaded by loom."));
```suggestion
		tasks.register("cleanLoomBinaries", CleanLoomBinaries.class, t -> t.setDescription("Removes binary jars created by Loom."));
		tasks.register("cleanLoomMappings", CleanLoomMappings.class, t -> t.setDescription("Removes mappings downloaded by Loom."));
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +			t.setDescription("Migrate mappings to a new version.");
```suggestion
			t.setDescription("Migrates mappings to a new version.");
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +			task.setDescription("Runs all loom cleanup tasks.");
```suggestion
			task.setDescription("Runs all Loom cleanup tasks.");
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +			t.setDescription("Remaps a Jar file.");
```suggestion
			t.setDescription("Remaps the built project jar to intermediary mappings.");
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +			t.setDescription("Generate a human-readable version of the Minecraft source.");
```suggestion
			t.setDescription("Generates a human-readable version of the Minecraft source.");
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +			t.setDescription("Generate an IntelliJ IDEA workspace from this project.");
```suggestion
			t.setDescription("Generates an IntelliJ IDEA workspace from this project.");
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +			t.setDescription("Generate Eclipse run configurations for this project.");
```suggestion
			t.setDescription("Generates Eclipse run configurations for this project.");
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +			t.setDescription("Remove Eclipse run configurations for this project.");
```suggestion
			t.setDescription("Removes Eclipse run configurations for this project.");
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +			t.setDescription("Opens this project in VSCode.");
```suggestion
			t.setDescription("Generates VSCode launch configurations.");
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +		tasks.register("remapSourcesJar", RemapSourcesJarTask.class, t -> t.setDescription("Remaps a source Jar."));
```suggestion
		tasks.register("remapSourcesJar", RemapSourcesJarTask.class, t -> t.setDescription("Remaps the project sources jar to intermediary names."));
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +			t.setDescription("Starts a development version of the Fabric client.");
```suggestion
			t.setDescription("Starts a development version of the Minecraft client.");
```

2020-05-29 14:55 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradlePlugin.java
> +			t.setDescription("Starts a development version of the Fabric server.");
```suggestion
			t.setDescription("Starts a development version of the Minecraft server.");
```

2020-05-29 15:26 UTC, Juuxel approved these changes

2020-05-29 16:30 UTC, modmuss50 approved these changes

2020-06-01 17:52 UTC, RDIL commented
cc my friend @liach

2020-06-01 18:08 UTC, merged