Made migrateMappings source-set aware and added an inPlace option
FabricMC/fabric-loom pull request #281
Opened 2020-09-19 00:34 UTC by shartte

2020-09-21 05:22 UTC, zml2008 requested changes
A few small things that stood out to me.

I was originally thinking each source set should be its own gradle task -- but loading, resolving, and merging mappings for every source set probably knocks out any efficiency gains that'd come from working in parallel.

This also fixes #246

2020-09-21 05:22 UTC, zml2008 commented on src/main/java/net/fabricmc/loom/task/MigrateMappingsTask.java
> +		sourceSets = new ArrayList<>();
Why not use the `Property` and `DomainObjectSet` API? Gradle seems to be preferring that api for its newer tasks, and some portion of the API exists in 4.10 already: https://docs.gradle.org/4.10.2/userguide/lazy_configuration.html

2020-09-21 05:22 UTC, zml2008 commented on src/main/java/net/fabricmc/loom/task/MigrateMappingsTask.java
> +		Path outputBaseDir = project.getBuildDir().toPath().resolve("remapped");
This should probably match up with the name of the task -- `mappingsMigrated` or something?

Also would be good to make this configurable.

2024-07-16 18:08 UTC, shartte commented
It's so far out of date, it doesn't make a lot of sense to update this 😓

2024-07-16 18:08 UTC, closed without merging