Use tiny-remapper to remap mixin annotation.
FabricMC/fabric-loom pull request #441
Opened 2021-07-19 03:15 UTC by LogicFan

This is pending https://github.com/FabricMC/tiny-remapper/pull/63 and I know the current implementation is far from correct. Need some input on how to correctly do it.

2021-07-28 14:17 UTC, LogicFan commented
Hi @modmuss50. Since the mixin extension is merged into tiny-remapper (though still pending release to maven), I want to discuss how this would work with loom. There are two problems need to discuss.

1. where do you want to put the option to enable/disable it. What I am currently thinking is to have
```
loom {
  useLegacyMixinAp = true; // do you want default to be true or false?
  mixinAp { // was "mixin" in the current version. Throw exception if "useLegacyMixinAp" is false.
  }
}
```
do you have any input on this?

2. the `sponge-mixin-0.9.4+mixin.0.8.3.jar` (maybe also other versions, haven't look at them yet) ships with `javax.annotation.processing.Processor`, which cause java compiler to try to start the mixin Ap regardless we set it or not. And even worse, since the related class file is not there, it will throw an exception. Is it possible to update these mixin jars without `javax.annotation.processing.Processor` service file?

2021-07-28 14:44 UTC, modmuss50 commented
Would be nice to enable this for everyone, but we will want to start rolling it out slowly. Loom 0.9 is basically done at this point so we could target 0.10 for this with it enabled for everyone.

2. If I understand what you are saying, not adding mixin to the `annotationProcessor` config is still causing it to try and load mixin when compling. That does sound really annoying. I will have to take a look myself at this as ideally we can contiune to support the mixin AP for a little bit. Worse case could loom add a dummy mixin AP that just doesnt crash? Idk without looking into it.

2021-07-28 15:32 UTC, LogicFan commented
> If I understand what you are saying, not adding mixin to the annotationProcessor config is still causing it to try and load mixin when compling.

Yes, that's what I mean. With a closer look at the loom, I think this causes the problem.

https://github.com/FabricMC/fabric-loom/blob/dev/0.9/src/main/java/net/fabricmc/loom/configuration/LoomDependencyManager.java#L193-L205

What's the reason we want to put these dependencies in the ap config? I guess we should be able to delete it just fine, as the `fabric-mixin-extension` will pull mixin ap anyway.

2021-07-28 15:44 UTC, modmuss50 commented
Thats used to add deps (mainly asm I think) onto the classpath for mce/mixin. That wont be needed if mixin AP's is not being used 👍 will be good to get rid of that.

2021-07-28 15:48 UTC, LogicFan commented
Just curious, shouldn't the `processor` version of mixin have all those dependencies available? Why does the `fabric-mixin-extension` pulls the `mixin` and add these dependencies manually? I think it can pull the `mixin-processor` directly and avoid adding these dependencies.

2021-07-29 21:53 UTC, LogicFan commented
This one is ready to review.

2021-07-31 22:50 UTC, modmuss50 requested changes

2021-07-31 22:50 UTC, modmuss50 commented on src/main/java/net/fabricmc/loom/api/LoomGradleExtensionAPI.java
> +	void mixinAp(Action<MixinApExtensionAPI> action);
Why the rename?

2021-07-31 22:50 UTC, modmuss50 commented on src/main/java/net/fabricmc/loom/api/LoomGradleExtensionAPI.java
> +	Property<Boolean> getUseLegacyMixinAp();
I would put this in the MixinApExtensionAPI, possibly rename `MixinApExtensionAPI` to `MixinExtensionAPI` makes more sense to me to put all mixin related options under that.

2021-07-31 22:50 UTC, modmuss50 commented on src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java
> +			if (extension.getUseLegacyMixinAp().get()) {
```
if (!extension.getUseLegacyMixinAp().get()) {
   return
}
```

Would be a little neater, this is fine tho.

2021-07-31 22:50 UTC, modmuss50 commented
Please also target the exp/0.10 branch. We can possiblly look at backporting this disabled by default as it should be quite safe.

2021-08-01 03:43 UTC, LogicFan commented
fixed all review items.

2021-09-05 15:10 UTC, modmuss50 commented
Where are we at with this? Does this depend on https://github.com/FabricMC/tiny-remapper/pull/75 and loader changes? Or is that a seprate thing?

2021-09-05 15:10 UTC, modmuss50 approved these changes

2021-09-06 02:02 UTC, LogicFan commented
This one is good to go. FabricMC/tiny-remapper#75 is a separate thing and won't affect this (It's to solve https://github.com/FabricMC/fabric/commit/2e359e933a5a3e188c90c14f286d578f2aad290c and I'm still working on it).

2021-09-07 10:28 UTC, merged