Use Property in LoomGradleExtension & Move task groups to constants
FabricMC/fabric-loom pull request #445
Opened 2021-07-24 17:59 UTC by shedaniel

Replacing the getters and setters is quite annoying since we have to choose a different name for the methods.

Using properties allow us to finalize and freeze values that should not be changed after evaluation (see finalizeValue)

2021-07-24 18:04 UTC, modmuss50 commented
Awesome 👍 This was the next thing I had planned for this. Will take a propper look later.

Wonder if it would be worth to show a message when using a deprecated method similar to gradles? Idk if gradle has an api for that that we could re-use.

Do any of the tests need updating?

2021-07-24 18:05 UTC, shedaniel commented
Gradle's deprecation setup is unfortunately internal: https://github.com/gradle/gradle/blob/master/subprojects/logging/src/main/java/org/gradle/internal/deprecation/DeprecationLogger.java

2021-07-24 18:51 UTC, modmuss50 commented
Should be easy enough to impliment some basic sort of warning.

Gradle does Expose the warning mode via: `Project.getGradle().getStartParameter().getWarningMode()`. Fail and None are just the two i'd worry about. Should be easy enough to log or crash with that.  Idk how long we want to keep it deprecated? Remove in 0.11?

2021-07-24 21:08 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/configuration/accesswidener/AccessWidenerJarProcessor.java
> +		File awPath = loomGradleExtension.getAccessWidenerPath().getAsFile().get();
Haven't tested this, but `get().getAsFile()` might be a bit more efficient since afaik there's no intermediate provider instance created then.

2021-07-24 21:08 UTC, Juuxel commented on src/test/resources/projects/dependencyResolutionManagement/projmap/build.gradle
> +	accessWidener.set file("src/main/resources/modid.accesswidener")
Fyi, `=` works with properties in the groovy dsl. Also, shouldn't this be `accessWidenerPath`?

2021-07-24 21:08 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/util/DeprecationHelper.java
> +					project.getLogger().lifecycle("Deprecated Loom APIs were used in this build, making it incompatible with future versions of loom. "
```suggestion
					project.getLogger().lifecycle("Deprecated Loom APIs were used in this build, making it incompatible with future versions of Loom. "
```

2021-07-25 21:53 UTC, modmuss50 commented
Change looks good, seems a few of the intergration tests are failing now. (they are all ran with warn-mode to set to fail)

2021-07-25 22:03 UTC, Juuxel reviewed
A few more comments, great PR though (`Property` for tasks next? :smile:)

2021-07-25 22:03 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/api/LoomGradleExtensionAPI.java
> +	default void addDecompiler(LoomDecompiler decompiler) {
This and `shareCaches` are probably fine to keep on their own since they're utility methods and not direct getters or setters.

2021-07-25 22:03 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/api/LoomGradleExtensionAPI.java
> +	ListProperty<LoomDecompiler> getLoomDecompilers();
Maybe `gameDecompilers` or `minecraftDecompilers`? `loom { loomDecompilers.add(...) }` is a bit awkward

2021-07-25 22:03 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/api/LoomGradleExtensionAPI.java
> +	RegularFileProperty getAccessWidenerPath();
Re-introducing `accessWidener` as an alias for this in the future would be nice, I think. (though not necessary)

2021-07-26 18:12 UTC, Juuxel approved these changes

2021-07-26 18:12 UTC, Juuxel commented on src/test/resources/projects/mixinApAutoRefmap/build.gradle
>  	mixin {
```suggestion
	mixin {
		defaultRefmapName = "refmap0000.json"
```

2021-07-26 18:12 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/api/LoomGradleExtensionAPI.java
> +	default void addJarProcessor(JarProcessor processor) {
The comment about utility methods also applies here (sorry, didn't notice this before) but it's really just a matter of opinion whether these are kept.

2021-07-26 19:05 UTC, Juuxel requested changes

2021-07-26 19:05 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/api/LoomGradleExtensionAPI.java
> +		getDeprecationHelper().replaceWithInLoom0_11("jarProcessors", "gameJarProcessors");
```suggestion
```

2021-07-26 19:07 UTC, modmuss50 approved these changes

2021-07-26 19:08 UTC, merged