Add dev config with default jar task on it, to aid with depending on …
FabricMC/fabric-loom pull request #525
Opened 2021-10-25 18:19 UTC by modmuss50

…sub projects.

Dpeneding on a sub project is now just `project(path: ":name", configuration: "namedElements")`.

2021-10-26 09:41 UTC, shedaniel approved these changes

2021-10-26 10:53 UTC, Juuxel requested changes

2021-10-26 10:53 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java
> +		extension.createLazyConfiguration(Constants.Configurations.DEV);
Should be declared `canBeResolved = false; canBeConsumed = true`

2021-10-26 10:53 UTC, Juuxel commented
`dev` is a bit generic of a name, so I wonder if it'll conflict a lot with existing configurations declared by users? You could always go with `devElements` to mirror `apiElements`/`runtimeElements`. But a good change nonetheless :rocket:

2021-10-26 11:09 UTC, modmuss50 commented
I was unsure on it conflicting, `named`, `namedOutputs` or `namedElements` might make more sense?

2021-10-26 11:11 UTC, Juuxel commented
`namedOutputs` and `namedElements` would both be good imo. "outputs" is clear to the user, but "elements" does follow the gradle conventions, which might be good as well.

2021-10-28 22:01 UTC, Juuxel approved these changes

2021-10-28 22:01 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java
> +		// Add the "dev" jar to the "dev" configuration
```suggestion
		// Add the "dev" jar to the "namedElements" configuration
```

2021-10-29 12:29 UTC, merged