Add multi project optimisation option to allow opting into shared tiny remapper.
FabricMC/fabric-loom pull request #747
Opened 2022-10-29 19:13 UTC by modmuss50

Im not 100% sure on the name, happy for other suggestions.

This option should be enabled in projects with many (5+) sub projects. This has been made opt-out due to fundamental issues raised. The peformance hit for most people with no sub projects will be 0, projects with a small handful of subprojects should only be a tiny bit slower.

2022-10-29 19:38 UTC, Juuxel commented
> The peformance hit for most people with no sub projects will be 0
Might actually be faster if there's one less task to run (haven't checked yet)

2022-10-29 19:48 UTC, Juuxel requested changes

2022-10-29 19:48 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/task/AbstractRemapJarTask.java
> +	protected LoomGradleExtension getLoomExtension() {
This should also be `@ApiStatus.Internal`

2022-10-29 19:48 UTC, Juuxel commented on src/main/java/net/fabricmc/loom/LoomGradleExtension.java
> +	boolean multiProjectOptimisation();
Would benefit from a javadoc comment like this:

```
If true, multi-project optimisation mode is enabled. This mode makes builds with many Loom projects
much faster by increasing sharing and disabling some functionality.

<p>You can enable it by setting the Gradle property {@code fabric.loom.multiProjectOptimisation} to {@code true}.
```

2022-11-01 21:36 UTC, modmuss50 commented
Going to merge, test failures are unrealted. 👍

2022-11-01 21:36 UTC, merged